services:
  postgresql:
    build: docker/postgresql
    ports:
      # Update as needed -- postgres will be available on localhost:6432
      # (to avoid conflicts with any other local instance)
      - "127.0.0.1:6432:5432"
    environment:
      # Not recommended, but easy, and fine for local dev.
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - app-network

networks:
  app-network:
